[build]
  publish = "_site/"


[[redirects]]
  from = "/neopolitan/*"
  to = "/neodoc/"
  status = 301
  force = true

[[headers]]
for = "/*"
[headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
